# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce3b7bb280fec0536290525013067fe6111b2c4d8c7affdb64326c3dfb183aabd35fb5c176ecc8df1b1ade4dfdce3ab928dea7b21fbea47108914bc0c86855bd

test:
  secret_key_base: e20008e48d78b98e07ad570b815ec59e3eeff6604d1f368b7bedf250a4ed10dae769749ba54dc9607b2d840c1ddb6ae4af7d2166b533d69c5d92bed614a97217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
