# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f4d14608d7de54bcedb65c2b29ef54b2188f3737846fb411eda8e904028f8e9bf9481b22e968fe15238889a564d2e0d7140a884a2dcfe8dfcc57df829582c6

test:
  secret_key_base: 8f1a4e86cd34bb6f8a580c1e74c5e4500d4068fb9547296b8d37602d97c83e34568a6668cd6c6a442237c38ba3356ecd664fab67d0d4d77578b2adffa31c2737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
