# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b211a9ad9ab3452f97f401a151131136a1ee1f32ddaac469dc1125cbc1fed6714c05e7b59ba4cdcbfa4fc6552dff2fbdfaba42f0035751197e1b65a409955157

test:
  secret_key_base: 3421fd1a490e3c438eddcf828a5290b3940b138cb5f45c9b82fd6cb9fe5823dc09a77ae39a7c6ab2e642edc40d7aeeb9378a12d16b018157d0e5eb60479a0c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
