# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb2e7ea475dce66736cb0b8495ab3b59f7ac55ea1c038378e5808cfdf861d501b76682567ba0cadbc9c86a4e760fa4a1d61cf2c1f423f0dc170453b9d87d75b4

test:
  secret_key_base: 713bc43155f7d31f9d8bf1e53e88a570b48a44963b0d7dd19b6a3ed8744ace8e52b9476de980c02bf975a450b4516fadd20c4052de7314074bd3685a34670fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
