# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d6a1d03279f98ee17118f822dbcce356041c28e6ffc70c35dda1c867a736436185c9e2bdf878e2834b84c9df8e07ada8c48b8d34a689a6a3cf1727f1415302

test:
  secret_key_base: 4eb9288071919cce906cc65e803b51dd7640025a67616b77948fd8e92faf0a6d46525e5e73836af789a59ad41fa7c79119a27f0215a52b45c0f3c590b429af7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
